// file: request.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: new_request_modify_label_type_one.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewOrderModifyLabelTypeOne struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time    int32  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Userid  int32  `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	PriceE4 string `protobuf:"bytes,3,opt,name=price_e4,json=priceE4,proto3" json:"price_e4,omitempty"` // change label type of price from int32 to string
	Desc    string `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
}

func (x *NewOrderModifyLabelTypeOne) Reset() {
	*x = NewOrderModifyLabelTypeOne{}
	if protoimpl.UnsafeEnabled {
		mi := &file_new_request_modify_label_type_one_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewOrderModifyLabelTypeOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewOrderModifyLabelTypeOne) ProtoMessage() {}

func (x *NewOrderModifyLabelTypeOne) ProtoReflect() protoreflect.Message {
	mi := &file_new_request_modify_label_type_one_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewOrderModifyLabelTypeOne.ProtoReflect.Descriptor instead.
func (*NewOrderModifyLabelTypeOne) Descriptor() ([]byte, []int) {
	return file_new_request_modify_label_type_one_proto_rawDescGZIP(), []int{0}
}

func (x *NewOrderModifyLabelTypeOne) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *NewOrderModifyLabelTypeOne) GetUserid() int32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *NewOrderModifyLabelTypeOne) GetPriceE4() string {
	if x != nil {
		return x.PriceE4
	}
	return ""
}

func (x *NewOrderModifyLabelTypeOne) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

var File_new_request_modify_label_type_one_proto protoreflect.FileDescriptor

var file_new_request_modify_label_type_one_proto_rawDesc = []byte{
	0x0a, 0x27, 0x6e, 0x65, 0x77, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x6d, 0x6f,
	0x64, 0x69, 0x66, 0x79, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f,
	0x6f, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x77, 0x6f, 0x72, 0x6c, 0x64, 0x22, 0x77, 0x0a, 0x1a, 0x4e, 0x65, 0x77, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65,
	0x4f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x65, 0x34, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x72, 0x69, 0x63, 0x65, 0x45, 0x34, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65,
	0x73, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_new_request_modify_label_type_one_proto_rawDescOnce sync.Once
	file_new_request_modify_label_type_one_proto_rawDescData = file_new_request_modify_label_type_one_proto_rawDesc
)

func file_new_request_modify_label_type_one_proto_rawDescGZIP() []byte {
	file_new_request_modify_label_type_one_proto_rawDescOnce.Do(func() {
		file_new_request_modify_label_type_one_proto_rawDescData = protoimpl.X.CompressGZIP(file_new_request_modify_label_type_one_proto_rawDescData)
	})
	return file_new_request_modify_label_type_one_proto_rawDescData
}

var file_new_request_modify_label_type_one_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_new_request_modify_label_type_one_proto_goTypes = []interface{}{
	(*NewOrderModifyLabelTypeOne)(nil), // 0: helloworld.NewOrderModifyLabelTypeOne
}
var file_new_request_modify_label_type_one_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_new_request_modify_label_type_one_proto_init() }
func file_new_request_modify_label_type_one_proto_init() {
	if File_new_request_modify_label_type_one_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_new_request_modify_label_type_one_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewOrderModifyLabelTypeOne); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_new_request_modify_label_type_one_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_new_request_modify_label_type_one_proto_goTypes,
		DependencyIndexes: file_new_request_modify_label_type_one_proto_depIdxs,
		MessageInfos:      file_new_request_modify_label_type_one_proto_msgTypes,
	}.Build()
	File_new_request_modify_label_type_one_proto = out.File
	file_new_request_modify_label_type_one_proto_rawDesc = nil
	file_new_request_modify_label_type_one_proto_goTypes = nil
	file_new_request_modify_label_type_one_proto_depIdxs = nil
}
